# Cargo.toml (Of wrapper around JEPA for images implementation)

[package]
name = "ijepa" # JEPA for images
version = "0.1.0"
edition = "2021"

[dependencies]
# Crates
jepa = { path = "./implementation" } # Path to your jepa crate
numrs = { path = "./lib/numrs" } # Path to your numrs crate
argsv = { path = "./lib/argsv-rust/lib/rust/argsv/" }
png = { path = "./lib/PNG-rust/lib/rust/png/" }
